workflows:
  ios-workflow:
    name: Desenrola AI - iOS Build & Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BACKEND_URL: "https://dating-app-production-ac43.up.railway.app"
        XCODE_PROJECT: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.desenrolaai.app"
        KEYBOARD_BUNDLE_ID: "com.desenrolaai.app.keyboard"

    working_directory: flutter_keyboard

    scripts:
      - name: Set up code signing
        script: |
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CM_CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          keychain initialize
          app-store-connect fetch-signing-files com.desenrolaai.app \
            --type IOS_APP_STORE \
            --create
          app-store-connect fetch-signing-files com.desenrolaai.app.keyboard \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Initialize iOS project
        script: |
          flutter create --org com.desenrolaai --project-name desenrola_ai_keyboard --platforms ios .
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - lucasfbpioli@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
