workflows:
  ios-workflow:
    name: Desenrola AI - iOS Build & Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BACKEND_URL: "https://dating-app-production-ac43.up.railway.app"
        BUNDLE_ID: "com.desenrolaai.app"
        KEYBOARD_BUNDLE_ID: "com.desenrolaai.app.keyboard"

    working_directory: flutter_keyboard

    scripts:
      - name: Initialize iOS project
        script: |
          # Save custom files
          cp -r ios/FlirtKeyboardExtension /tmp/KeyboardExtension
          cp ios/Runner/AppDelegate.swift /tmp/AppDelegate.swift
          # Remove incomplete ios dir and regenerate
          rm -rf ios
          flutter create --org com.desenrolaai --project-name app --platforms ios .
          # Fix bundle ID in Xcode project (flutter create generates com.desenrolaai.app)
          # Restore custom files
          mkdir -p ios/FlirtKeyboardExtension
          cp -r /tmp/KeyboardExtension/* ios/FlirtKeyboardExtension/
          cp /tmp/AppDelegate.swift ios/Runner/AppDelegate.swift
          # Set display name
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Desenrola AI" ios/Runner/Info.plist

      - name: Set up code signing
        script: |
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CM_CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
          app-store-connect fetch-signing-files $KEYBOARD_BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - lucasfbpioli@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
