workflows:
  ios-workflow:
    name: Desenrola AI - iOS Build & Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: codemagic

    environment:
      flutter: stable
      xcode: latest

      groups:
        - codemagic  # Deve conter CERTIFICATE_PRIVATE_KEY
        - ios_secrets  # Deve conter KEY_FRAGMENTS_SWIFT

      vars:
        BUNDLE_ID: "com.desenrolaai.app"

    working_directory: flutter_keyboard

    scripts:
      - name: Initialize iOS project
        script: |
          # Preserve custom files
          cp ios/Runner/AppDelegate.swift /tmp/AppDelegate.swift
          if [ -f GoogleService-Info.plist ]; then
            cp GoogleService-Info.plist /tmp/GoogleService-Info.plist
          fi
          # Preserve keyboard extension
          if [ -d "ios/FlirtKeyboardExtension" ]; then
            cp -r ios/FlirtKeyboardExtension /tmp/FlirtKeyboardExtension
          fi

          rm -rf ios
          flutter create --org com.desenrolaai --project-name app --platforms ios .

          # Disable scene-based lifecycle (new Flutter generates SceneDelegate which
          # breaks our custom AppDelegate that accesses window?.rootViewController).
          # Keep SceneDelegate.swift so Xcode can compile it, but remove the manifest
          # so iOS uses the traditional AppDelegate lifecycle instead.
          /usr/libexec/PlistBuddy -c "Delete :UIApplicationSceneManifest" ios/Runner/Info.plist 2>/dev/null || true

          # Restore custom files
          cp /tmp/AppDelegate.swift ios/Runner/AppDelegate.swift
          if [ -f /tmp/GoogleService-Info.plist ]; then
            cp /tmp/GoogleService-Info.plist ios/Runner/GoogleService-Info.plist
          fi
          # Restore keyboard extension
          if [ -d "/tmp/FlirtKeyboardExtension" ]; then
            cp -r /tmp/FlirtKeyboardExtension ios/FlirtKeyboardExtension
          fi

          # Set iPhone only (remove iPad support)
          sed -i '' 's/TARGETED_DEVICE_FAMILY = "1,2"/TARGETED_DEVICE_FAMILY = 1/g' ios/Runner.xcodeproj/project.pbxproj

          # Skip export compliance prompt (app only uses standard HTTPS/TLS)
          /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" ios/Runner/Info.plist

          # Set app display name (flutter create --project-name app sets it to "App")
          /usr/libexec/PlistBuddy -c "Set :CFBundleName Desenrola AI" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string Desenrola AI" ios/Runner/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Desenrola AI" ios/Runner/Info.plist

          # Contacts permission for WhatsApp contact import
          /usr/libexec/PlistBuddy -c "Add :NSContactsUsageDescription string 'Desenrola AI usa seus contatos para importar nome e telefone de contatos do WhatsApp.'" ios/Runner/Info.plist

      - name: Write KeyFragments.swift from secret
        script: |
          echo "$KEY_FRAGMENTS_SWIFT" > ios/FlirtKeyboardExtension/KeyFragments.swift
          echo "KeyFragments.swift written ($(wc -c < ios/FlirtKeyboardExtension/KeyFragments.swift) bytes)"

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test --reporter compact

      - name: Generate app icons (iOS only)
        script: |
          # Temporarily disable Android icons (no android/ dir in iOS-only build)
          sed -i '' 's/android: true/android: false/' pubspec.yaml
          dart run flutter_launcher_icons
          git checkout pubspec.yaml

      - name: Generate native splash screen
        script: |
          dart run flutter_native_splash:create

      - name: Add keyboard extension to Xcode project
        script: |
          gem install xcodeproj
          ruby scripts/add_keyboard_extension.rb
          echo "--- Xcode project targets ---"
          xcodebuild -project ios/Runner.xcodeproj -list 2>/dev/null || true
          echo "--- Extension files ---"
          ls -la ios/FlirtKeyboardExtension/ || true

      - name: Set up keychain and fetch signing files
        script: |
          keychain initialize
          # Fetch signing for main app
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          # Fetch signing for keyboard extension
          app-store-connect fetch-signing-files "com.desenrolaai.app.keyboard" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - lucasfbpioli@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
