workflows:
  ios-workflow:
    name: Desenrola AI - iOS Build & Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        - codemagic  # Deve conter CERTIFICATE_PRIVATE_KEY

      vars:
        BUNDLE_ID: "com.desenrolaai.app"

    working_directory: flutter_keyboard

    scripts:
      - name: Initialize iOS project
        script: |
          cp ios/Runner/AppDelegate.swift /tmp/AppDelegate.swift
          rm -rf ios
          flutter create --org com.desenrolaai --project-name app --platforms ios .
          cp /tmp/AppDelegate.swift ios/Runner/AppDelegate.swift

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate Podfile and install pods
        script: |
          flutter precache --ios
          cd ios && pod install

      - name: Set up keychain and fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - lucasfbpioli@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
